language: python
python:
- '3.4'
env:
  matrix:
  - FLIT_USERNAME=shir0kamii
  global:
    secure: o81Zpsjxvo27Sb4dEMHuJeOtUVknwxMAQNM16bTiq4zazbRKMKHdqs8x9LEDut3NthWOrfIQMTq2dY7mWiM9KAr4eP8lJuK3/abahsHgGGqom79GsvX7ux8OW9HvG0kU6prun/uLdOtlkJBDhKywMDhP1x7Lhn00kvnobZCO0afzGfR3AjOD9LdM6NYOuVMTeLoKw3cbmRbV1xmAa7eUKtZ5b6NmPaj7Kq0z2mFuemqmnlNIzYGo5AScWaTKhlM7x1tj8xx87reiKUWP2vJhqD7O0QuFuOnpYMvlJ2Cqek46NdFxn6PnNs2eNRtEldbAztGlV/50gZMY+ipgq4wvdp8qbgfQuUz4XooPkpduYSyCY2iwDQccC72MYXwOuZ6JhZPCjZ1AVVCiXQchaVzTQUSFLOo1y+p7E4GuFfJJ/hpYXY642p0X2NP7+52FsneVFKCB2/FvaFYgLsTgPB7bwqkaeamkFdsE9spQ18BQL2fWiCEs0EjfGpdbdQ7rfHvBawkX4krwZUn7wR9ad89jAav3In+TosrpEtykp2mE8UM2lbIS+AUQgefKEh3xGY+LX+d5gdQimCmSKDzhIXoTbDXUzBTEtAvvXvEuU9Y7xADbzhgQZJFGGBgkka+xl6Qr6rDkOaRRq7pUNMl1AVPvEjZ9zVLmKJhJp/V8Tc+pUmY=
before_install: pip install flit
install: flit install --deps all
script: true
after_success: "./autopublish.sh"
